name: NiceTV 网络直播电视
description: 一款网络直播电视、音视频播放器
full_description: '<br>
<br>更多功能:
<br>- 无限制添加订阅源
<br>- 支持m3u/txt格式订阅源
<br>- 支持画中画、倍速播放
<br>- 支持硬件解码
android: https://play.google.com/store/apps/details?id=com.goodiptv.app
iOS: https://apps.apple.com/app/nicetv-iptv-video-player/id6473073296

screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
